import { sequelize } from "./sequelize";
import { Note } from "../models/Note";

const userId = process.argv[2];
if (!userId) {
  console.error("❌ Usage: tsx backend/src/db/seed.ts <userId>");
  process.exit(1);
}

const notes = [
  // --- Development & Programming ---
  { title: "TypeScript generics cheat sheet", content: "Use <T> to parameterize types. Constrain with 'extends'. Default with =. Example: function identity<T>(x: T): T { return x; }. Useful for reusable utilities and API wrappers.", summary: "Quick reference for TypeScript generic syntax and patterns.", tags: ["typescript", "dev"] },
  { title: "REST vs GraphQL", content: "REST: simple, cacheable, resource-based URLs. GraphQL: single endpoint, client-specifies shape, solves over/under-fetching. Use REST for simple CRUD, GraphQL when clients have varying data needs.", summary: "Comparison of REST and GraphQL architectural styles.", tags: ["api", "dev", "graphql"] },
  { title: "PostgreSQL indexing tips", content: "Add indexes on columns used in WHERE, JOIN, ORDER BY. Partial indexes for filtered queries. EXPLAIN ANALYZE to profile. Avoid over-indexing — writes become slower.", summary: "Key strategies for optimizing PostgreSQL query performance.", tags: ["database", "postgres", "performance"] },
  { title: "Docker compose cheat sheet", content: "docker compose up -d: start detached. docker compose logs -f: follow logs. docker compose exec app sh: shell into container. volumes: persist data across restarts.", summary: "Essential Docker Compose commands for day-to-day use.", tags: ["docker", "devops"] },
  { title: "Git rebase vs merge", content: "Merge preserves history with a merge commit. Rebase rewrites commits onto the target branch for a linear history. Use rebase for feature branches before merging, merge for integrating long-lived branches.", summary: "When to use git rebase vs git merge.", tags: ["git", "dev"] },
  { title: "Node.js event loop notes", content: "Call stack → Node APIs → Callback queue → Event loop. Microtasks (Promise, queueMicrotask) run before macrotasks (setTimeout, setInterval). Never block the event loop with sync heavy ops.", summary: "How the Node.js event loop processes async operations.", tags: ["nodejs", "javascript", "dev"] },
  { title: "React Query key patterns", content: "Use arrays as keys: ['todos', userId]. Invalidate with queryClient.invalidateQueries(['todos']). Prefetch with prefetchQuery. Stale time controls background refetch frequency.", summary: "Best practices for structuring React Query cache keys.", tags: ["react", "frontend", "dev"] },
  { title: "CSS Grid quick reference", content: "grid-template-columns: repeat(3, 1fr). Place items: grid-column: 1 / 3. Named areas: grid-area: header. Auto-fill vs auto-fit: auto-fit collapses empty tracks.", summary: "CSS Grid layout properties and practical patterns.", tags: ["css", "frontend"] },
  { title: "Async/await error handling", content: "Wrap in try/catch or use .catch() on the async function call. Create a helper: const [err, data] = await to(promise). Never swallow errors silently in catch blocks.", summary: "Patterns for robust async/await error handling in JS.", tags: ["javascript", "dev"] },
  { title: "Zod schema patterns", content: "z.object({ name: z.string().min(1), age: z.number().int().positive() }). Use .parse() to throw or .safeParse() to get result. Transform with .transform(). Extend schemas with .extend().", summary: "Common Zod schema patterns for runtime validation.", tags: ["typescript", "validation", "dev"] },

  // --- Architecture & Design ---
  { title: "Clean Architecture layers", content: "Entities → Use Cases → Interface Adapters → Frameworks. Dependency rule: inner layers know nothing about outer. Domain logic must not import from infrastructure.", summary: "Core principles of Clean Architecture layering.", tags: ["architecture", "design"] },
  { title: "SOLID principles summary", content: "S: Single responsibility. O: Open/closed. L: Liskov substitution. I: Interface segregation. D: Dependency inversion. Each class should have one reason to change.", summary: "Brief explanation of each SOLID design principle.", tags: ["architecture", "oop", "design"] },
  { title: "Event-driven architecture", content: "Producers emit events. Consumers subscribe. Decouple services. Use message brokers (Kafka, RabbitMQ). Design idempotent consumers. Handle out-of-order events gracefully.", summary: "Key concepts and trade-offs in event-driven systems.", tags: ["architecture", "backend"] },
  { title: "CQRS pattern notes", content: "Command Query Responsibility Segregation: separate write model (commands) from read model (queries). Read model can be denormalized for performance. Write model enforces business rules.", summary: "CQRS pattern overview and when to apply it.", tags: ["architecture", "design", "backend"] },
  { title: "Repository pattern in TypeScript", content: "Define an interface: IUserRepository { findById(id: string): Promise<User> }. Implement with Sequelize/Prisma. Inject via constructor for testability. Keeps domain free of ORM concerns.", summary: "How to implement the Repository pattern with TypeScript.", tags: ["architecture", "typescript", "design"] },

  // --- Productivity & Workflows ---
  { title: "Daily deep work schedule", content: "8–10am: deep work block (no meetings, no Slack). 10–11am: emails & messages. 11am–1pm: second deep work block. 2–4pm: meetings allowed. 4–5pm: planning next day.", summary: "Time-blocking schedule optimized for deep focus work.", tags: ["productivity", "workflow"] },
  { title: "Weekly review checklist", content: "1. Clear inbox to zero. 2. Review project list. 3. Check calendar for next week. 4. Update task priorities. 5. Identify top 3 goals for the week. 6. Archive completed notes.", summary: "Steps for a thorough weekly review session.", tags: ["productivity", "review"] },
  { title: "Pomodoro technique notes", content: "25 min focus, 5 min break × 4 = long 15–30 min break. Track completed pomodoros. Interrupt = restart timer. Best for tasks with clear deliverables. Not great for flow-state work.", summary: "How to apply the Pomodoro technique effectively.", tags: ["productivity", "focus"] },
  { title: "Inbox zero strategy", content: "Process, not store. Reply if <2 min. Delegate with a forwarded note. Defer to task manager. Delete or archive. Check email only 2–3x/day at set times.", summary: "System for maintaining inbox zero consistently.", tags: ["productivity", "email"] },
  { title: "Note-taking with Zettelkasten", content: "Fleeting notes → Literature notes → Permanent notes. Each note is atomic (one idea). Link related notes. No folders — use tags and links. Ideas emerge from connections.", summary: "Overview of the Zettelkasten knowledge management system.", tags: ["productivity", "notes", "learning"] },

  // --- Learning & Books ---
  { title: "Designing Data-Intensive Applications — highlights", content: "Chapter 3: B-trees for reads, LSM-trees for writes. Chapter 5: replication lag and consistency models. Chapter 8: distributed systems fallacies. Essential for backend engineers.", summary: "Key takeaways from DDIA by Martin Kleppmann.", tags: ["books", "learning", "database"] },
  { title: "The Pragmatic Programmer — key lessons", content: "DRY: don't repeat yourself. Orthogonality: isolate changes. Tracer bullets over prototypes. Automate everything. Invest in your knowledge portfolio regularly.", summary: "Core lessons from The Pragmatic Programmer.", tags: ["books", "learning", "dev"] },
  { title: "Clean Code highlights", content: "Functions should do one thing. Name variables for readability. Avoid comments — write self-documenting code. Keep functions small. Boy Scout rule: leave code cleaner than you found it.", summary: "Key takeaways from Clean Code by Robert C. Martin.", tags: ["books", "learning", "dev"] },
  { title: "Atomic Habits — core ideas", content: "1% better every day = 37x better in a year. Identity-based habits. Four laws: make it obvious, attractive, easy, satisfying. Habit stacking: after X, I will Y.", summary: "Framework and key insights from Atomic Habits.", tags: ["books", "learning", "habits"] },
  { title: "Deep Work — main arguments", content: "Deep work is rare and valuable. Shallow work is email, meetings, admin. Schedule deep work like meetings. Quit social media or limit to batched sessions. Embrace boredom.", summary: "Cal Newport's case for cultivating deep work ability.", tags: ["books", "learning", "productivity"] },
  { title: "Staff Engineer — career notes", content: "Four archetypes: tech lead, architect, solver, right hand. Influence without authority is the core skill. Write technical strategy documents. Sponsor others actively.", summary: "Career advice for senior engineers from Staff Engineer.", tags: ["books", "learning", "career"] },
  { title: "The Mom Test — startup interviews", content: "Don't ask if people like your idea. Ask about their life, problems, past behavior. 'Would you pay for this?' is a bad question. Specifics beat hypotheticals.", summary: "How to run customer discovery interviews that don't lie.", tags: ["books", "learning", "startup"] },
  { title: "System Design Interview vol 2 — notes", content: "Covered: proximity service (geohash), nearby friends (WebSocket), ad click aggregation (Kafka + MapReduce), hotel reservation (optimistic locking). Good for infra pattern vocabulary.", summary: "System design patterns from Alex Xu's volume 2.", tags: ["books", "learning", "system-design"] },

  // --- System Design ---
  { title: "Rate limiting strategies", content: "Token bucket: allows bursts. Leaky bucket: smooth output. Fixed window: simple but boundary spikes. Sliding window log: precise but memory heavy. Use Redis for distributed rate limiting.", summary: "Comparison of rate limiting algorithms and implementations.", tags: ["system-design", "backend"] },
  { title: "URL shortener design", content: "Base62 encode a counter or hash. Store mapping in KV store (Redis + DB). Handle redirects with 301 (cacheable) or 302 (trackable). Scale reads with CDN caching.", summary: "Core design decisions for a URL shortening service.", tags: ["system-design", "backend"] },
  { title: "Notification system design", content: "Components: API servers, message queues per channel (email, SMS, push), worker pools, retry with exponential backoff. Deduplication with idempotency keys. Rate-limit per user.", summary: "High-level design of a multi-channel notification system.", tags: ["system-design", "backend"] },
  { title: "Search autocomplete design", content: "Trie for prefix search. Limit depth, cache top-k per node. Update trie asynchronously from logs. Serve from CDN edge. Debounce client queries at 300ms.", summary: "Design considerations for a search autocomplete feature.", tags: ["system-design", "search"] },
  { title: "Distributed cache patterns", content: "Write-through: write cache + DB together. Write-behind: async DB write. Read-through: cache populates on miss. Cache-aside (lazy loading): app manages cache. Eviction: LRU, LFU.", summary: "Caching strategies and when to apply each.", tags: ["system-design", "caching", "performance"] },

  // --- AI & Machine Learning ---
  { title: "Prompt engineering basics", content: "Be specific and structured. Provide examples (few-shot). Chain of thought: 'think step by step'. Role prompting: 'You are an expert in...'. Iterate and log what works.", summary: "Fundamentals of writing effective LLM prompts.", tags: ["ai", "llm", "prompts"] },
  { title: "RAG architecture notes", content: "Retrieval-Augmented Generation: embed documents → store in vector DB → query embeds user input → retrieve top-k chunks → inject into LLM context. Reduces hallucination for factual tasks.", summary: "How RAG systems work and when to use them.", tags: ["ai", "llm", "architecture"] },
  { title: "Vector database comparison", content: "Pinecone: managed, easy. Weaviate: open-source, rich filtering. Qdrant: fast, Rust-based. pgvector: stay in Postgres. Choose based on scale, filtering needs, and infra preference.", summary: "Comparison of popular vector database options.", tags: ["ai", "database", "dev"] },
  { title: "Fine-tuning vs prompting", content: "Prompting: fast, flexible, no training cost. Fine-tuning: better style/format adherence, reduces prompt length, requires labeled data. Start with prompting; fine-tune only if needed.", summary: "When to fine-tune an LLM vs engineer better prompts.", tags: ["ai", "llm"] },
  { title: "AI features for Note AI", content: "Ideas: auto-summarize on save, tag suggestions from content, semantic search with embeddings, daily digest of recent notes, ask a question about your notes (RAG).", summary: "Planned AI-powered features for the Note AI app.", tags: ["ai", "note-ai", "ideas"] },

  // --- Frontend ---
  { title: "React performance checklist", content: "memo() for expensive pure components. useMemo for expensive calculations. useCallback to stabilize handlers. Virtualize long lists (react-virtual). Code-split with lazy(). Profile with React DevTools.", summary: "Checklist for diagnosing and fixing React performance issues.", tags: ["react", "frontend", "performance"] },
  { title: "TailwindCSS v4 migration notes", content: "@theme replaces tailwind.config.js. Use CSS variables for tokens. 'container' is now a utility. Dark mode: use @media or class strategy. Some plugin APIs changed.", summary: "Key changes when migrating from Tailwind v3 to v4.", tags: ["css", "tailwind", "frontend"] },
  { title: "shadcn/ui component patterns", content: "Use <Dialog>, <Sheet> for overlays. <Command> for search. <Form> with react-hook-form + zod. Customize via className, not variant props. Copy-paste, don't install as dep.", summary: "Patterns for working effectively with shadcn/ui components.", tags: ["frontend", "ui", "react"] },
  { title: "React Router v7 notes", content: "Route-based code splitting built-in. Loaders replace useEffect data fetching. Actions handle form submissions. Use <Form> component for progressive enhancement. Type-safe with generatePath.", summary: "Key changes and patterns in React Router v7.", tags: ["react", "frontend", "routing"] },
  { title: "Vite config tips", content: "Alias: resolve.alias { '@': path.resolve(__dirname, 'src') }. Proxy: server.proxy for API. Build chunks: manualChunks in rollupOptions. Env: import.meta.env.VITE_* only.", summary: "Useful Vite configuration options and patterns.", tags: ["vite", "frontend", "dev"] },

  // --- Career & Growth ---
  { title: "Technical interview prep plan", content: "Week 1–2: arrays, strings, hashmaps. Week 3–4: trees, graphs, BFS/DFS. Week 5: dynamic programming. Week 6: system design. Do 2 LeetCode mediums/day. Mock interviews on week 6.", summary: "6-week structured plan for technical interview preparation.", tags: ["career", "interview"] },
  { title: "Engineering manager 1:1 agenda", content: "Status updates (5min). Blockers (10min). Career goals progress (10min). Feedback exchange (5min). Action items recap. Keep it collaborative, not a status report.", summary: "Structured agenda template for effective 1:1 meetings.", tags: ["career", "management"] },
  { title: "Building in public — notes", content: "Share what you're working on weekly. Document failures, not just wins. Build an audience before you need it. Short-form for engagement, long-form for depth. Consistency > perfection.", summary: "Strategy for building in public as a developer.", tags: ["career", "personal-brand"] },
  { title: "Salary negotiation notes", content: "Always negotiate. Give a range, not a single number. Anchor high. Don't reveal current salary if possible. Get competing offers. Consider total comp: equity, bonus, PTO, remote flexibility.", summary: "Key tactics for negotiating compensation effectively.", tags: ["career", "finance"] },
  { title: "Code review best practices", content: "Reviewer: be kind, ask questions, not demand. Review logic, not style (use linters). Approve with nits. Author: small PRs, link to issue, explain 'why'. Respond to every comment.", summary: "Guidelines for giving and receiving code reviews well.", tags: ["career", "dev", "workflow"] },

  // --- Personal & Lifestyle ---
  { title: "Morning routine v2", content: "5:30 wake. No phone for 30 min. 10 min stretching. Cold shower. Journal 3 gratitudes + today's top goal. Coffee + 30 min reading before any work starts.", summary: "Revised morning routine optimized for energy and focus.", tags: ["personal", "habits", "routine"] },
  { title: "Gym program — current split", content: "Monday: push (chest, shoulders, triceps). Tuesday: pull (back, biceps). Wednesday: legs. Thursday: rest. Friday: push. Saturday: pull. Sunday: legs or rest.", summary: "Current PPL gym training split.", tags: ["personal", "fitness", "health"] },
  { title: "Meal prep Sunday checklist", content: "Cook grains (rice, quinoa). Roast vegetables. Prep protein (chicken breast, eggs). Portion into containers. Prepare snacks (fruit, nuts). Total time: ~2 hours.", summary: "Weekly meal prep routine for healthy eating.", tags: ["personal", "food", "health"] },
  { title: "Books to read this quarter", content: "An Elegant Puzzle (Will Larson). A Philosophy of Software Design (Ousterhout). Never Split the Difference (Voss). The Art of Doing Science and Engineering (Hamming). Range (Epstein).", summary: "Reading list for Q3 across engineering and personal development.", tags: ["books", "personal", "learning"] },
  { title: "Travel wishlist", content: "Tokyo in spring (cherry blossoms). Lisbon for the weather and food. Kyoto temples and matcha. Istanbul for the history. Norway fjords in summer. Tbilisi for the architecture and wine.", summary: "Destinations to visit ranked by interest.", tags: ["personal", "travel"] },
  { title: "Budget breakdown — monthly", content: "Rent: 40%. Food: 15%. Subscriptions: 5%. Savings: 20%. Investments: 10%. Entertainment: 5%. Misc: 5%. Goal: increase investments to 15% next quarter.", summary: "Current monthly budget allocation and financial goals.", tags: ["personal", "finance"] },
  { title: "Arabic learning progress", content: "Completed Duolingo section 2. Started Pimsleur Arabic Level 1. Can read basic MSA. Watching Al Jazeera with subtitles. Next: find a language exchange partner on Tandem.", summary: "Arabic learning milestones and next steps.", tags: ["personal", "language", "learning"] },

  // --- Projects ---
  { title: "Note AI — project roadmap", content: "Phase 1: auth + notes CRUD ✅. Phase 2: AI summarization + tagging. Phase 3: semantic search. Phase 4: tasks & projects. Phase 5: mobile app (React Native). Public launch after Phase 3.", summary: "High-level roadmap for the Note AI application.", tags: ["note-ai", "project", "roadmap"] },
  { title: "Note AI — API contract v1", content: "GET /api/v1/notes — list all. POST /api/v1/notes — create. GET /api/v1/notes/:id — single. PUT /api/v1/notes/:id — update. DELETE /api/v1/notes/:id — delete. All require Bearer token.", summary: "REST API specification for notes endpoints.", tags: ["note-ai", "api", "backend"] },
  { title: "Note AI — UI design decisions", content: "Glass morphism cards. Dark-first design. Tailwind v4 + shadcn. Sidebar navigation on desktop, bottom nav on mobile. Smooth transitions, not flashy animations. Accessibility: WCAG 2.1 AA.", summary: "Frontend design system and UX decisions for Note AI.", tags: ["note-ai", "frontend", "design"] },
  { title: "Portfolio website redesign", content: "Tech: Astro + TailwindCSS. Sections: hero, projects, writing, contact. Add case studies for 3 projects. Performance: 100 Lighthouse score. Deploy on Vercel. Launch by end of month.", summary: "Plan for redesigning personal portfolio site.", tags: ["project", "portfolio", "frontend"] },
  { title: "Side project ideas", content: "1. AI commit message generator. 2. CLI for managing dotfiles. 3. Habit tracker with streak visualization. 4. Open-source TypeScript form validation lib. 5. Resume parser API.", summary: "List of potential side project ideas to explore.", tags: ["project", "ideas", "dev"] },

  // --- Meetings & Standup Templates ---
  { title: "Weekly team sync template", content: "Agenda: last week wins (10min), blockers (10min), this week priorities (10min), open discussion (10min). Keep async-first: share written updates before meeting.", summary: "Reusable agenda template for weekly engineering team syncs.", tags: ["workflow", "meetings", "template"] },
  { title: "Architecture decision record template", content: "Title. Status (proposed/accepted/deprecated). Context (why). Decision (what). Consequences (trade-offs). Keep ADRs in /docs/adr. Numbered sequentially.", summary: "Template for writing Architecture Decision Records (ADRs).", tags: ["architecture", "template", "workflow"] },
  { title: "Post-mortem template", content: "Incident summary. Timeline. Root cause analysis. Impact. What went well. What went wrong. Action items (owner, deadline). Share within 48h of resolution.", summary: "Template for conducting blameless post-mortems.", tags: ["workflow", "template", "devops"] },
  { title: "Pull request template", content: "What: describe change in 1-2 sentences. Why: link to issue or explain context. How: highlight non-obvious implementation choices. Testing: what was tested manually or in unit tests. Screenshots if UI.", summary: "Standard PR description template for the team.", tags: ["workflow", "git", "template"] },

  // --- Security ---
  { title: "Auth security checklist", content: "Hash passwords with bcrypt (cost ≥ 12). Use HTTPS everywhere. Rotate JWT secrets. Short-lived access tokens + refresh tokens. Rate-limit login attempts. Log failed auth events.", summary: "Security checklist for authentication implementation.", tags: ["security", "auth", "backend"] },
  { title: "OWASP Top 10 — quick notes", content: "1. Broken access control. 2. Crypto failures. 3. Injection (SQL, XSS). 4. Insecure design. 5. Security misconfiguration. 6. Outdated components. 7. Auth failures. 8. Integrity failures. 9. Logging failures. 10. SSRF.", summary: "Brief overview of each OWASP Top 10 vulnerability.", tags: ["security", "dev"] },
  { title: "Securing Express APIs", content: "Use helmet for headers. Enable CORS selectively. Sanitize inputs with zod/joi. Parameterize SQL queries. Rate-limit with express-rate-limit. Log request anomalies. Never expose stack traces.", summary: "Practical security hardening steps for Express.js APIs.", tags: ["security", "nodejs", "backend"] },

  // --- DevOps & Infrastructure ---
  { title: "CI/CD pipeline design", content: "Stages: lint → test → build → deploy (staging) → smoke test → deploy (prod). Use feature flags for risky releases. Rollback strategy: redeploy previous image. All steps in under 10 min.", summary: "Design principles for a reliable CI/CD pipeline.", tags: ["devops", "cicd"] },
  { title: "GitHub Actions tips", content: "Cache node_modules with actions/cache. Use matrix builds for multi-version testing. Secrets via ${{ secrets.MY_KEY }}. Reusable workflows with workflow_call. Limit permissions per job.", summary: "Useful patterns and tips for GitHub Actions workflows.", tags: ["devops", "github", "cicd"] },
  { title: "Monitoring checklist", content: "Metrics: error rate, latency (p50/p95/p99), throughput, saturation. Logs: structured JSON, correlation IDs. Alerts: page only on actionable signals. Dashboard per service.", summary: "Key observability components for production services.", tags: ["devops", "monitoring", "backend"] },
  { title: "Nginx as reverse proxy — config notes", content: "proxy_pass http://app:3000. Set headers: X-Real-IP, X-Forwarded-For. Gzip compression. Rate limit zones. SSL termination at Nginx. Cache static assets with expires max.", summary: "Nginx reverse proxy configuration notes for Node apps.", tags: ["devops", "nginx", "infrastructure"] },

  // --- Miscellaneous ---
  { title: "Coffee brewing guide — pour over", content: "Ratio: 1:15 (coffee:water). Grind: medium-coarse. Water temp: 93°C. Bloom 45s with 2× coffee weight water. Total brew: 3–4 min. V60 or Chemex. Use filtered water.", summary: "Step-by-step guide for pour over coffee brewing.", tags: ["personal", "coffee", "guide"] },
  { title: "Ergonomics setup checklist", content: "Monitor: eye level, arm's length. Chair: feet flat, knees 90°. Keyboard: elbows 90°, neutral wrists. Take 5-min breaks every 45 min. Use f.lux or dark mode at night. Standing desk 30% of day.", summary: "Checklist for an ergonomic home office setup.", tags: ["personal", "health", "setup"] },
  { title: "Vim motions to memorize", content: "w/b: word forward/back. ci': change inside quotes. dap: delete a paragraph. gg/G: top/bottom. <C-d>/<C-u>: half page down/up. * to search word under cursor. :s/old/new/g to replace.", summary: "Essential Vim motions worth committing to muscle memory.", tags: ["dev", "tools", "vim"] },
  { title: "Terminal aliases — zsh", content: "alias gs='git status'. alias gaa='git add -A'. alias gcm='git commit -m'. alias gpo='git push origin'. alias nr='npm run'. alias ll='ls -lah'. alias ..='cd ..'.", summary: "Useful zsh aliases to speed up terminal workflow.", tags: ["dev", "terminal", "workflow"] },
  { title: "VS Code extensions I use", content: "ESLint, Prettier, GitLens, Error Lens, REST Client, Thunder Client, Tailwind CSS IntelliSense, TypeScript Hero, Todo Tree, Peacock (multi-project color coding).", summary: "Essential VS Code extensions for full-stack TypeScript development.", tags: ["dev", "tools", "vscode"] },
  { title: "Learning resources bookmark", content: "roadmap.sh for structured paths. The Odin Project for web dev. CS50 for fundamentals. System Design Primer on GitHub. Kent C. Dodds blog for React. ByteByteGo for system design.", summary: "Curated list of high-quality learning resources.", tags: ["learning", "resources"] },
  { title: "Keyboard shortcuts — macOS", content: "Cmd+Space: Spotlight. Cmd+Tab: switch apps. Cmd+`: cycle windows. Ctrl+Space: switch input. Cmd+Shift+5: screenshot. Ctrl+Cmd+Space: emoji picker. Cmd+Opt+Esc: force quit.", summary: "Must-know macOS keyboard shortcuts for efficiency.", tags: ["tools", "macos", "productivity"] },
  { title: "API testing with REST Client", content: "Create .http files. ### separates requests. @baseUrl = http://localhost:3000. Send: Ctrl+Alt+R. Save responses to file. Supports env variables via {{$dotenv VAR}}.", summary: "How to use the REST Client VS Code extension for API testing.", tags: ["dev", "tools", "api"] },
  { title: "Regex patterns I keep forgetting", content: "Email: /^[\\w.-]+@[\\w.-]+\\.[a-z]{2,}$/i. URL: /https?:\\/\\/[^\\s]+/. UUID: /[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}/i. Trim whitespace: /^\\s+|\\s+$/g.", summary: "Useful regex patterns for common validation scenarios.", tags: ["dev", "regex", "reference"] },
  { title: "HTTP status codes reference", content: "200 OK. 201 Created. 204 No Content. 301 Moved Permanently. 400 Bad Request. 401 Unauthorized. 403 Forbidden. 404 Not Found. 409 Conflict. 422 Unprocessable. 429 Too Many Requests. 500 Internal Server Error.", summary: "Quick reference for commonly used HTTP status codes.", tags: ["dev", "api", "reference"] },
  { title: "Environment variables best practices", content: "Never commit .env files. Use .env.example as a template. Prefix client vars with VITE_ or NEXT_PUBLIC_. Validate env at startup (with zod). Use different values per environment.", summary: "Best practices for managing environment variables securely.", tags: ["dev", "security", "workflow"] },
  { title: "Package.json scripts conventions", content: "dev: local dev server. build: production build. start: serve production build. test: run test suite. lint: ESLint check. format: Prettier write. db:seed: run seed script. db:migrate: run migrations.", summary: "Conventional npm script names and their meanings.", tags: ["dev", "nodejs", "workflow"] },
  { title: "JSON Web Tokens explained", content: "Header.Payload.Signature. Header: alg + typ. Payload: claims (sub, iat, exp). Signature: HMAC-SHA256 of header.payload with secret. Decode at jwt.io. Never store sensitive data in payload — it's readable.", summary: "How JWTs are structured and where to use them safely.", tags: ["auth", "security", "backend"] },
  { title: "Sequelize migration tips", content: "Use queryInterface.createTable / addColumn / removeColumn. Run with: npx sequelize-cli db:migrate. Rollback: db:migrate:undo. Keep migrations small and reversible. Never edit old migrations.", summary: "Tips for writing and managing Sequelize database migrations.", tags: ["database", "sequelize", "backend"] },
  { title: "CORS configuration notes", content: "Allow specific origins in production, never '*' with credentials. Expose headers as needed. Preflight OPTIONS must return 204. Use cors() middleware in Express before routes.", summary: "How to configure CORS correctly for a production API.", tags: ["backend", "security", "nodejs"] },
  { title: "localStorage vs sessionStorage vs cookies", content: "localStorage: persists after tab close, no expiry, 5MB. sessionStorage: cleared on tab close. Cookies: sent with requests, can be HttpOnly/Secure, 4KB limit. Use HttpOnly cookies for auth tokens.", summary: "Comparison of browser storage options and their use cases.", tags: ["frontend", "security", "dev"] },
  { title: "Debounce vs throttle", content: "Debounce: execute after last call + delay. Use for search inputs, resize handlers. Throttle: execute at most once per interval. Use for scroll events, rate-limited API calls. Both reduce unnecessary invocations.", summary: "Difference between debounce and throttle with use cases.", tags: ["javascript", "frontend", "performance"] },
  { title: "WebSocket vs Server-Sent Events", content: "WebSocket: full duplex, binary support, more complex. SSE: server → client only, built on HTTP, simpler. Use SSE for live feeds/notifications. Use WebSocket for chat, collaborative editing.", summary: "When to choose WebSocket over SSE for real-time features.", tags: ["backend", "realtime", "dev"] },
  { title: "TypeScript utility types reference", content: "Partial<T>: all optional. Required<T>: all required. Readonly<T>: immutable. Pick<T, K>: subset. Omit<T, K>: exclude. Record<K, V>: key-value map. ReturnType<F>: infer return. Parameters<F>: infer args.", summary: "Quick reference for TypeScript built-in utility types.", tags: ["typescript", "dev", "reference"] },
  { title: "Error handling patterns in Express", content: "Centralized error middleware: (err, req, res, next). Custom AppError class with statusCode + message. Wrap async handlers with a try/catch utility. Send consistent error shape: { error: { message, code } }.", summary: "Patterns for centralized error handling in Express applications.", tags: ["nodejs", "backend", "dev"] },
  { title: "Database transactions in Sequelize", content: "const t = await sequelize.transaction(). Pass { transaction: t } to all queries. Commit: await t.commit(). Rollback in catch: await t.rollback(). Use managed transactions for cleaner code.", summary: "How to use transactions in Sequelize for atomic operations.", tags: ["database", "sequelize", "backend"] },
];

async function seed() {
  try {
    console.log("🔄 Connecting to database...");
    await sequelize.authenticate();
    await sequelize.sync({ alter: true });

    console.log(`🌱 Seeding ${notes.length} notes for user: ${userId}`);

    const now = new Date();
    const records = notes.map((note, i) => ({
      ...note,
      userId,
      createdAt: new Date(now.getTime() - (notes.length - i) * 3_600_000),
      updatedAt: new Date(now.getTime() - (notes.length - i) * 3_600_000),
    }));

    await Note.bulkCreate(records);

    console.log(`✅ Seeded ${notes.length} notes successfully`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seed();
